### ISSUE TITLE
VOXEDIT: Model looks coorupted work with UE5.3

### ISSUE THREAD

**Issue by jerobarraco** [mgerhardy/vengi#313]
When importing a model on 5.3 it imports but the vertices are all corrupted.

this happens regardless of the flags used. i tested most combinations, quads, triangles, menge quads, vertex colors, textures, etc.
this behavior is specific to vengi, i don't get this issue with other tools.

[test vengi 5.3 2.txt](https://github.com/mgerhardy/vengi/files/12331148/test.vengi.5.3.2.txt)
[test vengi 5.3.txt](https://github.com/mgerhardy/vengi/files/12331149/test.vengi.5.3.txt)
[testvengi.zip](https://github.com/mgerhardy/vengi/files/12331150/testvengi.zip)

this image is from top view. notice the errors.
is completely unusable. on default view it simply break the view.
note: disregard the colors since i used the one with textures.

![image](https://github.com/mgerhardy/vengi/assets/3729895/901aec30-ae1f-4370-95c0-e9ec052393ec)

**Comment by mgerhardy** [comment]
thanks a lot for the report - should be fixed in [90d60de](https://github.com/mgerhardy/vengi/commit/90d60de3a7b3079da0a38fbf5b8c48c5191caacc)

**Comment by jerobarraco** [comment]
Awesome! Thanks!
this seems to be working fine on 5.3 (5.2 would still crash)
colors seems a bit off but i still have to play around to see if that's something to do with srgb vs linear
![image](https://github.com/mgerhardy/vengi/assets/3729895/993f2b4a-65b4-4703-8b4d-8cf41d16adf5)
![image](https://github.com/mgerhardy/vengi/assets/3729895/2a416cde-a4bf-4a1e-8f2c-7fe1800487f0)
![image](https://github.com/mgerhardy/vengi/assets/3729895/ae01e2a8-4e18-4794-9947-e702ce66a793)

**Comment by mgerhardy** [comment]
Thanks a lot for the feedback. Please let me know when I do something wrong with the colors.
